### ISSUE TITLE
Ingress from KubeAPI network policies cause auto-update issues on 0.32.1

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#1101]
The current code for updating KubeAPI netpols does not account for policies that do not have an egress block (i.e. ingress only policies). The lack of safety around the init code in particular results in crashes of the Pepr pods when an ingress policy is present.

**Comment by mjnagel** [comment]
An example policy that would cause this failure:
```
      - direction: Ingress
        selector:
          app.kubernetes.io/component: webhook
        remoteGenerated: KubeAPI
```
