### ISSUE TITLE
Expanded support for VirtualService generation

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-core#114]
### Is your feature request related to a problem? Please describe.
During our attempt to leverage the UDS Operator Package custom resource we ran into issue trying to support GitLab's VirtualService.  It is currently impossible to specify a [HttpMatch](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest) via the `Package`  `network.expose` which would be necessary to emulate GitLab's current VS.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab
  namespace: gitlab
spec:
  gateways:
  - istio-tenant-gateway/tenant-gateway
  hosts:
  - gitlab.uds.dev
  http:
  - fault:
      abort:
        httpStatus: 403
        percentage:
          value: 100
    match:
    - uri:
        prefix: /-/metrics
    route:
    - destination:
        host: gitlab-webservice-default.gitlab.svc.cluster.local
        port:
          number: 8181
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gitlab-webservice-default.gitlab.svc.cluster.local
        port:
          number: 8181
  - match:
    - uri:
        prefix: /admin/sidekiq
    route:
    - destination:
        host: gitlab-webservice-default.gitlab.svc.cluster.local
        port:
          number: 8080
```      

### Describe the solution you'd like

- **Given** a VirtualService that contains multi-port/prefix routes
- **When** a Package gets created to emulate the VirtualService is deployed
- **Then** A VirtualService is created that has multiple match statements routing traffic to multiple ports.

### Describe alternatives you've considered
I've considered that this complexity might not be appropriate to be supported by the `Package` custom resource and the advice might be to just not rely on the UDS operator to create a VirtualService.

### Additional context
The current implementation supports routing to a single service with a single port.  As a terrible example we could do something like this: 
```
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: gitlab-webservice-default
        podLabels:
          app: webservice
        gateway: tenant
        host: gitlab
        ports: 
          - number: 8181
            prefix: /
          - number: 8080
            prefix: /admin/sidekiq
```
