### ISSUE TITLE
Neuvector SSO Login with OpenID functionality can fail to come up.

### ISSUE THREAD

**Issue by docandrew** [defenseunicorns/uds-core#1215]
On an initial deployment of UDS-Core within a bundle, Neuvector failed to display the `Login with OpenID` button until the Controller pods were all restarted. Restarting the manager pod did not fix the issue. Once the Controller pods were restarted the app came back up and the `Login with OpenID` button was present. This is the first time I've witnessed this behavior so it may be difficult to trigger and could be related to some kind of timing or dependency issue. This was deployed on a single-node cluster.

### Environment
Device and OS: x86_64 Ubuntu 22.04
App version: UDS Core 0.34.0 / Neuvector 5.4.1
Kubernetes distro being used: RKE2

### Steps to reproduce
1. Perform UDS Core deployment, no additional Neuvector overrides.

### Expected result

Neuvector displays the "Login with OpenID" button when user logs on.

### Actual Result

No OpenID login button present.

### Visual Proof (screenshots, videos, text, etc)

On initial deployment:

![Image](https://github.com/user-attachments/assets/73f756f1-a367-4a49-a678-e7d83873195d)

After restarting Controller pods:

![Image](https://github.com/user-attachments/assets/238046b2-a8f9-43f7-9fb1-5921c9d8067a)

### Severity/Priority

Medium-ish. Would prefer not to have to restart controllers since this will ideally be a "hands-off" / no-kubectl-required deployment for the end users.

### Additional Info

The secret containing oidcinitcfg.yaml was present, contained the correct client ID and client secret, and I confirmed that the file was mounted at /etc/config/ in all the controller pods. Keycloak had the client ID configured properly. Restarting the controller pods resolved the issue.

**Comment by docandrew** [comment]
Noticed these logs present which appear to be common to this issue:

<img width="1200" alt="Image" src="https://github.com/user-attachments/assets/77daf463-c295-4836-98f3-caa989429e48" />

**Comment by mjnagel** [comment]
@docandrew if this is in a test/dev environment would you be willing to deploy with some overrides?
```yaml
packages:
  # Wherever your core package is, or the runtime-security func layer
  - name: core
...
    overrides:
      neuvector:
        core:
          values:
            - path: controller.env
              value:
                - name: NO_DEFAULT_ADMIN # Make sure to include this to disable the admin still
                  value: "1"
                - name: CTRL_PATH_DEBUG
                  value: "debug"
```

This will toggle on debug logging for the controller pods, hoping that we can get more info from that when the error occurs (from reviewing the upstream code it seems like there should be more logged out, just not sure if it will be helpful).
