### ISSUE TITLE
feat: Append DOMAIN to gateways

### ISSUE THREAD

**Issue by lemonprogis** [defenseunicorns/uds-core#1301]
### Is your feature request related to a problem? Please describe.
When deploying uds-core, gateways are created per ingress. There are different hosts added based on uds-core requirements (keycloak, sso etc). Something that has come up recently with a mission hero is that their UI needs to sit on the root domain (i.e. foo.example.com) which is not being set at the Gateway currently.

### Describe the solution you'd like

- **Given** the domain is set
- **When** gateway appends base domain to hosts array
- **Then** a user is able navigate to the base domain

### Describe alternatives you've considered
N/A

### Additional context

Not sure if it's as easy as this to include it, but more so what should be done for SSL certificates if this was to occur.

```yaml
{{- $domain := tpl .Values.domain . }}
{{- if .Values.tls }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.name }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name }}-ingressgateway
  servers:
    {{ range $name,$server := .Values.tls.servers }}
    - hosts:
        - "{{ $domain }}" # <--- add here
        {{- range $server.hosts | default (list "*") }}
        - "{{ . }}.{{ $domain }}"
        {{- end }}
      port:
        name: "http-{{ $name }}"
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - "{{ $domain }}" # <--- add here
        {{- range $server.hosts | default (list "*") }}
        - "{{ . }}.{{ $domain }}"
        {{- end }}
      port:
        name: "https-{{ $name }}"
        number: 443
        protocol: HTTPS
      tls:
        mode: {{ $server.mode }}
        {{- if ne $server.mode "PASSTHROUGH" }}
        credentialName: {{ $.Values.tls.credentialName | default "gateway-tls" | quote }}
        # if supportTLSV1_2 is both defined and true, use TLSV1_2, otherwise use TLSV1_3
        minProtocolVersion: {{ if $.Values.tls.supportTLSV1_2 }}TLSV1_2{{ else }}TLSV1_3{{ end }}
        {{- end }}
    {{ end }}
{{ end }}
```
