### ISSUE TITLE
Support Root Domain in Expose Key Package CR

### ISSUE THREAD

**Issue by joelmccoy** [defenseunicorns/uds-core#1641]
### Is your feature request related to a problem? Please describe.
UDS Core does not currently support setting up endpoint access at the root domain of the deployment via the package CRD.  For example if the root domain is `uds.dev` I can not expose Application A at `uds.dev`.  It would be nice to support this the `expose` key for the package CR.  You could maybe set `host: .` to indicate root domain?

It might look something like:
```yaml
spec:
  network:
    expose:
      - service: uds-registry
        selector:
          app: uds-registry
        host: . # maybe "." is reserved key for the root domain?
        gateway: tenant
        port: 8080
        targetPort: 8080
```

### Describe the solution you'd like

- **Given** a deployment of UDS Core
- **When** a package CR is created to expose an app at the root domain
- **Then** the app is accessible at the root domain url

### Describe alternatives you've considered
Manually create the VS to expose the app (this works fine, but it would be nice to have this in operator logic)

### Additional context
This is a use case that is popping up for the UDS Registry public service
