### ISSUE TITLE
Enable Package CR toggle for Istio Authorization Policies

### ISSUE THREAD

**Issue by TheFutonEng** [defenseunicorns/uds-core#1654]
### Is your feature request related to a problem? Please describe.
Some workloads need some lead time and test cycles before fully adopting Istio ambient mode.  Allowing a package developer the ability to turn off the `AuthorizationPolicy` generated by the UDS operator will make for a smoother adoption of ambient mode.

### Describe the solution you'd like

- **Given** Package CR with a flag set (IE `authPolicy: disabled`)
- **When** a package is deployed
- **Then** the UDS operator does not create an Authorization Policy

### Describe alternatives you've considered
Getting an entire mission to switch to ambient mode at once.  After that, I considered: flipping a Monopoly board, curling up in the corner and crying, deep breathing exercises, and converting to Buddhism.

For realsies, we considered: no ambient, mixed ambient, and fully ambient.  There is an appetite to get to fully ambient but it will take tiem.

### Additional context
Some more context [here](https://defense-unicorns.slack.com/archives/C06QJAUHWFN/p1750105023726979).

**Comment by mjnagel** [comment]
Waiting for more feedback on this. We may convert this to a documentation issue to note more on how these AuthPols work and "workarounds" if you have specific apps that aren't injected/following STRICT mTLS.

To document a few workarounds in this issue:
1. Mesh wide "opt-out" of authorization policies: This will effectively nullify any ALLOW authpols in your cluster. This is not ideal of course but is a more nuclear option that may be acceptable depending on risk. This effectively means you are relying entirely on network policies for network security, which do not have per-port granularity when ambient workloads are the "client" (even if the "server" workloads are still running in sidecar mode). DENY authorization policies can be used in addition as needed.
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: permissive-ap-namespace
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - {}
```

2. Namespace wide "opt-out" of authorization policies: This is the same as the above, but scoped to a specific namespace. This would allow you to maintain the strong protections on most workloads/namespaces, but opt some out:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: permissive-ap-namespace
  namespace: <package-namespace>
spec:
  action: ALLOW
  rules:
  - {}
```

3. Specific workload "opt-out" of authorization policies: Same as above, scoped even finer to a workload (based on selector):
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: permissive-ap-workload
  namespace: <package-namespace>
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      selector: for-app
```

4. Specific workload + port "opt-out" of authorization policies: Same as above, scoped even finer to a specific port, on a specific workload:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: permissive-ap-workload-port
  namespace: <package-namespace>
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports:
        - "1234"
  selector:
    matchLabels:
      selector: for-app
```

These all offer varying levels of flexibility to _effectively_ opt-out of authorization policies. While the operator would continue to generate authpols, these `ALLOW`s would be permissive enough to ensure that permissive (or even uninjected) traffic is still allowed without issue.
