### ISSUE TITLE
interface validation checks in ci

### ISSUE THREAD

**Issue by chance-coleman** [defenseunicorns/uds-core#211]
### Expected result
Grafana, Neuvector and Keycloak all have interface validation checks in their respective src/tasks.yaml. At this time they are commented out because CI does not create istio for the single package tests.

### Actual Result
Interface validations are not passing in ci, either they need to pass or not run with some sort of conditional logic. Their ideal for local testing, so maintaining them is worth the hassle.

### Related Issue
https://github.com/defenseunicorns/maru-runner/issues/66

**Comment by mjnagel** [comment]
Updating this ticket with some new changes - Istio now runs in all single package tests but we still have similar considerations for testing interactions with other pieces of the stack like monitoring/keycloak.

One avenue to help here is splitting validation into two separate test runs
- https://github.com/defenseunicorns/uds-core/blob/main/tasks/test.yaml#L15: This could run a task like `single-pkg-validate`
- https://github.com/defenseunicorns/uds-core/blob/main/tasks/test.yaml#L23: This could run the same `validate` or more aptly named `all-validate`/`e2e-validate`

Individual packages could then have tasks like:
```yaml
tasks:
  - name: single-pkg-validate
    actions:
      - cmd: <hit grafana VS>
      - cmd: <basic cypress test?>
  - name: all-validate
     actions:
       - task: single-pkg-validate
       - cmd: <sso login check>
       - cmd: <validate grafana dashboards / datasources>
```

This would allow us to reuse tests where it makes sense but also allow augmenting our full test suite without causing issues on the single package side.
