### ISSUE TITLE
Operator fails to generate all network policies for all virtual services if they use the same pod selector.

### ISSUE THREAD

**Issue by anthonywendt** [defenseunicorns/uds-core#466]
### Describe what should be investigated or refactored

Network policies that are generated for any virtual services that are created don't generate unique enough names.

The below section of code [linked here](https://github.com/defenseunicorns/uds-core/blob/7cf9c4c09dccc1d91edb7acbb2aee8750c5433ed/src/pepr/operator/controllers/network/policies.ts#L55-L39) creates policy descriptions that only use the selector and gateway to differentiate between policies. 

```js
  // Generate NetworkPolicies for any VirtualServices that are generated
  const exposeList = pkg.spec?.network?.expose ?? [];
  // Iterate over each exposed service, excluding directResponse services
  for (const expose of exposeList.filter(exp => !exp.advancedHTTP?.directResponse)) {
    const { gateway = Gateway.Tenant, port, selector = {}, targetPort } = expose;

    // Create the NetworkPolicy for the VirtualService
    const policy: Allow = {
      direction: Direction.Ingress,
      selector,
      remoteNamespace: `istio-${gateway}-gateway`,
      remoteSelector: {
        app: `${gateway}-ingressgateway`,
      },
      // Use the same port as the VirtualService if targetPort is not set
      port: targetPort ?? port,
      description: `${Object.values(selector)} Istio ${gateway} gateway`,
    };
```
When a name is generated in the second snippet of code [linked here](https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/operator/controllers/network/generate.ts#L119-L136) it uses that description. The problem here is if we need to create multiple virtual services that use the same pod selector but different ports, it will only create a network policy for the last virtual service as the names are not unique.
```js
export function generateName(policy: Allow) {
  const name =
    // Use the description if it exists
    policy.description ||
    // Otherwise use the direction, and combination of remote properties
    [
      Object.values(policy.selector || ["all pods"]),
      policy.remoteGenerated || [
        policy.remoteNamespace,
        Object.values(policy.remoteSelector || ["all pods"]),
      ],
    ]
      // Flatten the array
      .flat(1)
      .join("-");

  return `${policy.direction}-${name}`;
}
```
 There is a comment [linked here](https://github.com/defenseunicorns/uds-core/blob/main/src/pepr/operator/controllers/network/generate.ts#L12-L11) that states how its making the name unique by using values like port, but isn't accurate given the code.
 ```js
  // Create a unique name for the NetworkPolicy based on the package name, index, direction, pod labels, and port
  const name = generateName(policy);
```

We can get it to create all the needed network policies for each virtual service that is created by using a different label selector that is defined in the same pod. Clunky but works although it should work even if using the same selector.

This only creates the network policy for the last virtual service
```yaml
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: nexus
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: nexus-nexus-repository-manager
        selector:
          app: nexus-repository-manager
        gateway: tenant
        host: nexus
        port: 8081
      - service: nexus-nexus-repository-manager-docker-5000
        selector:
          app: nexus-repository-manager
        gateway: tenant
        host: nexus-docker
        port: 5000
```
This works and creates all network polices
```yaml
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: nexus
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: nexus-nexus-repository-manager
        selector:
          app: nexus-repository-manager
        gateway: tenant
        host: nexus
        port: 8081
      - service: nexus-nexus-repository-manager-docker-5000
        selector:
          app.kubernetes.io/instance: nexus
        gateway: tenant
        host: nexus-docker
        port: 5000
```
