### ISSUE TITLE
Add default values to crd documentation

### ISSUE THREAD

**Issue by Michael-Kruggel** [defenseunicorns/uds-core#614]
### Is your feature request related to a problem? Please describe.
When running `kubectl explain` it should say what the default is, if there is one

### Describe the solution you'd like

- **Given** I am using a pepr crd
- **When** I run `kubectl explain` on said crd
- **Then** All keys and what their defaults are is documented

### Additional context
An example is when running `kubectl explain package.spec.sso`, no default is listed for `protocol`

An example where it is explained `kubectl explain pod.spec`, specifically `preemptionPolicy` tells you what the default is.

**Comment by mjnagel** [comment]
I took a look at our CRD and it looks like defaults show up in the CRD yaml, where we have added them. For example:

```yaml
                    publicClient:
                      default: false
                      description: Defines whether the client requires a client secret
                        for authentication
                      type: boolean
```

However, those don't seem to surface in `kubectl explain`:

```console
❯ kubectl explain package.spec.sso.publicClient
GROUP:      uds.dev
KIND:       Package
VERSION:    v1alpha1

FIELD: publicClient <boolean>


DESCRIPTION:
    Defines whether the client requires a client secret for authentication
```

Looking at the provided example, `preemptionPolicy` lists its default value in the description, so we'd need to put this information into our descriptions for it to show there or potentially contribute to `kubectl` upstream to show this.
