### ISSUE TITLE
Release do not trigger a required test for branch protection

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/uds-core#65]

**Comment by mjnagel** [comment]
Unfortunately this is a github "limitation" - commits that are made using the `GITHUB_TOKEN` will not trigger workflows on a PR - https://github.com/orgs/community/discussions/25702#discussioncomment-3248819 . Since release-please is making these commits using the github token it doesn't trigger the workflow. The main documented alternative is to use a personal access token for these pushes instead, but I think that's pretty undesirable. Another solution is to use a github app to handle the release, still leveraging release-please but using the app token for commits. I think a similar effect could be accomplished using slash commands to trigger the workflow.

In the short term, making an empty commit to the release PR does trigger workflows, which is what we have been doing on the last few releases to make sure the tests run.

**Comment by mjnagel** [comment]
If we add:
```yaml
on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]
```

to our testing workflows this would fix our main issue by allowing us to put a milestone on the PR to kick off the workflows.
