### ISSUE TITLE
Loki gateway does not deploy on RKE2

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-core#68]
### Environment
Device and OS: ec2 instance, amazon linux 2023
App version: 0.6.2
Kubernetes distro being used: RKE2 1.27.x

### Steps to reproduce
1. Attempt to deploy the example uds-core bundle on an RKE2 cluster.
2. Loki gateway fails to become healthy with the error:
    ```
    nginx: [emerg] host not found in resolver "kube-dns.kube-system.svc.cluster.local."
    ```

### Expected result

Happy deploy!

### Actual Result

The loki gateway is configured to point at the DNS service in kube-system. The [default svc name](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L10) it expects is `kube-dns` and RKE2 has a different name (`rke2-coredns-rke2-coredns`).

### Severity/Priority

Medium? Completely blocks deployment after loki if the dns service is not named `kube-dns`, but with bundle overrides it could be changed.

### Additional Context

While this could be done with a variable it would be annoying to have to pass in an environment specific value like this. Ideally a standard service could be created that maps to the DNS pods in cluster already?

**Comment by jbrewer3** [comment]
Dropping override example here for those hitting issues.

```
- name: uds-core
    repository: oci://ghcr.io/defenseunicorns/packages/uds/core
    ref: 0.10.0-upstream
    overrides:
      loki:
        loki:
          values:
            # Override default dns service name for Loki Gateway
            - path: "global.dnsService"
              value: "rke2-coredns-rke2-coredns"
```
