### ISSUE TITLE
Add envoyfilter for trimming trailng dots from domains

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-core#688]
### Is your feature request related to a problem? Please describe.
Currently there are cases where istio doesn't handle domain names with a trailing dot correctly. (destinationRule and serviceEntry) unless explicitly specfiied, this force duplication of said resources.

### Describe the solution you'd like

Add the below envoyFilter so that envoy strips the trailing dot and on the base domain names are necessary in istio resources

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: strip-trailing-dot
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          strip_trailing_host_dot: true
```

### Describe alternatives you've considered
The current workaround is to duplicate all istio resources with a trailing dot to guarantee functionality
