### ISSUE TITLE
Add automatic destination rule and service entry creation for headless http services via pepr

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-core#689]
### Is your feature request related to a problem? Please describe.

From what myself, @mjnagel, and @Racer159 can see istio doesn't work correctly in the context of headless services with http ports. When there is a headless service that uses http and another service wants to access a specific pod under the svc it will form a request with a url like `pod-1.headless-svc.namespace.svc.cluster.local`. This fails with `NR filter_chain_not_found` at the destination pod sidecar. The current fix is to add a `serviceEntry` and `destinationRule` for each replica in the headless service. This obviously does not scale as the creation of istio resources is not directly tied to the scaling of pods.

I think this is solvable by pepr via watching pods, cross referencing with headless services that have http ports, and dynamically creating/removing `serviceEntry` and `destinationRule` resources when the pods scale.

### Describe the solution you'd like

- **Given** a headless service with http ports
- **When** a pod that matches the selector of the headless service is created or destroyed
- **Then** `serviceEntry` and `destinationRule` resources are created/destroyed according to the event

### Additional context
Example `serviceEntry` and `destinationRule`:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
    name: pod-0-headless
spec:
  hosts:
  - pod-0.headless-svc.namespace.svc.cluster.local
  ports:
  - number: 8080
    name: http-admin
    protocol: HTTP
  resolution: NONE
  location: MESH_INTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: pod-0-headless
spec:
  host: pod-0.headless-svc.namespace.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: pod-0.headless-svc.namespace.svc.cluster.local
```
