### ISSUE TITLE
Unable to upgrade Keycloak after Velero Backup / Restore

### ISSUE THREAD

**Issue by tworcester** [defenseunicorns/uds-core#718]
### Environment
Device and OS: RHEL 8
App version: [v0.24.1]
Kubernetes distro being used: zarf k3s 1.28
Other:

### Steps to reproduce
1. Deploy UDS-core (With velero configured for EnableCSI, in this case I was using aws-ebs-csi-driver)
2. trigger backup `k -n velero exec -it deploy/velero -- velero backup create --from-schedule=velero-udsbackup`
3. stand up another cluster
4. Deploy UDS-core (Ideally you would just install Velero, but I didn't have access to just that zarf package)
5. trigger restore `k -n velero exec -it deploy/velero -- velero restore create --from-backup=<reference> --existing-resource-policy=update --include-namespaces=keycloak`
6. try to install UDS-core to a newer version (or the same)

### Expected result
Successful upgrade of UDS-core on a cluster with velero restored UDS-core components.

### Actual Result
PVCs that are restored have these fields in the spec due to the restoration options:
```yaml
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-keycloak-data-12345
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-keycloak-data-12345
```

When you try to re-install or upgrade to a new version, the Keycloak deployment fails saying that these fields are immutable.

### Visual Proof (screenshots, videos, text, etc)
N/A

### Severity/Priority
High - I vote this is pretty high since Velero is supposed to be the disaster recovery mechanism if an entire cluster goes down.  This bug would prevent you from ever doing updates/maintenance on UDS-core

### Additional Context
N/A
