### ISSUE TITLE
Allow VirtualService Configuration with Multiple Match -> Prefix -> Routes

### ISSUE THREAD

**Issue by anthonywendt** [defenseunicorns/uds-core#975]
### Is your feature request related to a problem? Please describe.
Currently you can only configure a virtual service to route to one service. I would like to be able to configure a single virtual service to route to multiple services that can match to a uri.

### Describe the solution you'd like

I would like to be able to create a virtual service spec like this.

```
Spec:
  Gateways:
    istio-tenant-gateway/tenant-gateway
  Hosts:
    my-app.uds.dev
  Http:
    Match:
      Uri:
        Prefix:  /api
    Route:
      Destination:
        Host:  my-app-api
        Port:
          Number:  80
    Match:
      Uri:
        Prefix:  /
    Route:
      Destination:
        Host:  my-app-frontend
        Port:
          Number:  80
```
